### ISSUE TITLE
[UX/UI] Column / Table tabs on right side panel

### ISSUE THREAD

**Issue by lusebille** [gristlabs/grist-core#1011]
The ‘Table / Colonne’ choice stuff is not very UX friendly , It may be clearer if when you select a cell or column it switching automatically to ‘Column’ because if user click a column he probably want to edit it 

https://github.com/gristlabs/grist-core/assets/170542975/281f4648-2e8f-45eb-a062-479dbc1e0c0e

**Comment by manuhabitela** [comment]
Shimming in on this (not sure if you'd prefer specific accessibility-related issues @lusebille?)

I'd say the visual way of telling us what is the current tab between "Table" and "Column" is misleading. The unselected tab has the same background as the tab content, and is in bold text. 

We also can argue the only way we are visually told about the selected tab is a color change. So what is the selected tab: the colored one, or the one matching the content background + having bold text?

One clearer way to show current tab would be something like this, with border and color change, no border between current tab and content, and the bold text being the selected tab (there are still small color issues in the screenshot but this is to get a broad idea).

![373606761-8ce84a79-9d49-48a7-8baa-25e7ec46a8d3](https://github.com/user-attachments/assets/f060a9b8-b6c4-45a7-b5ad-d803e9b91cb6)

**Comment by lusebille** [comment]
Ok with that UI evolution, I added a tag 'accessibility' @manuhabitela so you can use it ( but you may not have editing rights I don't know) , I made this mock based on your proposal but adding green to icon https://www.figma.com/design/wcpetFt6aOKzTszcvPPWLQ/%5B05%2F24%5D-Grist-Design?node-id=1769-59987&t=NGpS8UWkP5gvIPOv-1

Anyway ( to not forget it) the main topic of this ticket is ' As a user I want to lead on 'column' tab when I click on a cell' (today user stay ob 'table' tab )

**Comment by dsagal** [comment]
This issue has two parts, so let me comment separately:

## Styling tabs

Confirming that the updated design for the tabs in the creator panel (as in the figma link above) is approved, and ready to implement. This one:

<img width="687" alt="Screenshot 2024-10-15 at 21 39 01" src="https://github.com/user-attachments/assets/6f87a6d2-a84b-4e2e-bab7-2f47a17901ab">

Don't forget to test dark mode.

This part is a good first issue. I'll mark it as such.

## Switching tabs on selection

The other part of this task is: when the creator panel is open, and a column in table widget is selected (`GridView#selectColumn` method), then automatically switch the tab in the creator panel to Column. When the full table is selected (`GridView#selectAll` method), then switch the tab in the creator panel to Table. Other cases (e.g. for other widgets, or when selecting cells) are not so clear, so let's not make other changes at this time.

It would make sense to implement this part separately from styling. Since this is a new behavior, it needs some test case(s) written, and user testing to check that there are no bad surprises.

**Comment by lusebille** [comment]
I'm adding another styling change proposal for sub tabs in creator panel : 

![Image](https://github.com/user-attachments/assets/a3d8d7b3-7cd3-4eb0-9f15-c4424e472d43)

here are the mocks for this proposal : https://www.figma.com/design/wcpetFt6aOKzTszcvPPWLQ/%5B05%2F24%5D-Grist-Design?node-id=2660-107595&t=qX4iHFYd8uzsW8kZ-1

**Comment by lusebille** [comment]
I reviewed it , it's fine for me 👍
