### ISSUE TITLE
Cannot add everyone@getgrist.com as a member of an organisation.

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#1023]
We would like to allow everyone be able to consult (with read-only access) our templates org (aka team site).

However, the code only allows the `support` special account to add `everyone@getgrist.com` as a member of an org:
https://github.com/gristlabs/grist-core/blob/a304b2262355a26cd8b0990ac362628583b1b1bc/app/gen-server/lib/HomeDBManager.ts#L3674-L3677

But there is no problem adding `anon@getgrist.com` (maybe because they cannot create persistant documents ?). That means that our user should be logged out to see our templates :stuck_out_tongue: 

Would it be possible to allow `everyone@getgrist.com` be a member of an org without having to work do that using the `support` user (maybe with at most read-only access? Or also giving the same latitude than for `support` to the super-admin?), which necessitates to do some hairy manipulations? 

I wanted to create this issue before opening a PR to understand everything that motivates the current behavior.

**Comment by paulfitz** [comment]
The restriction for who can share with `everyone@getgrist.com` is there I think because of some implication about what resources become listed. For example, when a user asks the API for a list of everything they have access to, it is possible that sites shared with `everyone@getgrist.com` will be reported? (I'm not sure, haven't thought about this corner of Grist for a long time).

We needed to reduce the possibility of spam, where users could "inflict" their sites on others. I don't remember the details, just that the current situation is not well thought out when it commons to whether a resource should be listed for others or not.

**Comment by fflorent** [comment]
Thanks @paulfitz  for your answer. That makes sense.

We took a look at the documentation and at the code, it seems safe to set `GRIST_SUPPORT_EMAIL` to an existing account, there would be no mess (rights or scope collision), the account will get more rights. 

We will test that. Thanks! :)
