### ISSUE TITLE
[cosmetic bug] Sort order in Reference column popup menu is random

### ISSUE THREAD

**Issue by asitemade4u** [gristlabs/grist-core#112]
- I have a table **Status**, which is ordered by `name`. The names each begin with a number (eg: `2.save`, `5.transferred`, etc.) which allows me to sort them naturally
- I have another table, **ToDo** which quotes the table Status as a Reference column
- The records in the page where ToDo is displayed as a grid are sorted by the Reference column `Status:name`
- When I click in the Reference column `Status:name`, I get a popup menu with all possible values in the table Status. But these values are randomly ordered:

![image](https://user-images.githubusercontent.com/11460106/145271659-f4c8bb91-b9e7-4868-ae66-6aac66d6d66c.png)

I get it for the first value in the list (which was in fact `1.detect` in the cell before I clicked) but what about the second value in the list (`4.transferred to db`)?

And even though, I gess the right way to display the popup menu would be to select the prexisting cell value (here: `1.detect`) at its right location in the menu.

**Comment by asitemade4u** [comment]
I should add that when the cell is empty, the order of the popup menu in the Reference column is correct:

![image](https://user-images.githubusercontent.com/11460106/145275338-c9249ca6-4d50-4eaf-85d9-bbe761c2ef90.png)

**Comment by dsagal** [comment]
The reason for this is that the dropdown functions as an auto-complete: rather than list all choices in the column, it lists the closest matches, by quality of match, and then other choices alphabetically, up to 50 total.

In this case, it looks strange, admittedly, because the second match it found is another choice that starts with the same letter "d" as the text in the cell (the highlighted letter "D" is the telling sign). That seems like such a weak match that it makes it look random.

We could maybe clarify the current behavior by inserting a line separator between items that match at all (i.e. first 2 in your example), and items that don't, and perhaps a light-grey text explaining that the rest are "Items with no matches".

I don't see a way to combine auto-complete behavior with an always-ordered list in general. But we can consider options to configure the behavior. E.g.
- use pure select behavior, i.e. list all options alphabetically (even if there are thousands), without trying to bring best matches to the front (only scroll to the one best match)
- match whole items rather than by words (then typing "save" wouldn't bring "2.save" to the front, and only typing in "2" would).

Does any of this sound like a worthwhile improvement? Anyone have other ideas?

**Comment by asitemade4u** [comment]
Wow, I did not expect such a complex behavior.
No matter what, this was a "cosmetic" bug, so absolutely no need to search for a "solution".
