### ISSUE TITLE
Load failed, failed to fetch errors on reverse proxy site

### ISSUE THREAD

**Issue by skinnylatte** [gristlabs/grist-core#149]
Hi, Grist seems super cool and I am very excited to replace Airtable with a self-hosted solution.

I am running this docker-compose file. I have swag set up and I am able to access https://sheets.my.tld.

However, I am unable to load the application. In Chrome, I get "There was an error: failed to fetch", and in Safari I get "There was an error: Load failed". Any ideas on how I can troubleshoot?

```  
grist:
    image: gristlabs/grist
    container_name: grist
    restart: unless-stopped
    environment: 
      - PUID=1000
      - PGID=1000
      - DEBUG=1
      - TIMEZONE=Americas/Los_Angeles
      - GRIST_DOMAIN=sheets.my.tld
      - GRIST_DEFAULT_EMAIL=myname@myemail.com
      - APP_DOC_URL=sheets.my.tld
      - APP_HOME_URL=sheets.my.tld
      - GRIST_SINGLE_ORG=docs 
      - GRIST_ORG_IN_PATH=true
    volumes:
      - ./appdata/grist:/config
      - $CONFIG/grist:/persist
    ports:
      - 8484:8484
    networks:
      - proxy 
   ```

**Comment by skinnylatte** [comment]
To clarify: I can access IP:8484, but when I try to go to those domains I get the errors.

**Comment by paulfitz** [comment]
Hi @skinnylatte, the APP_*_URLs need a protocol at the beginning, like http[s]://sheets.my.tld. If that turns out to be the problem, you may hit another one just after that, depending on networking. If you have trouble opening a document,  see https://github.com/gristlabs/grist-core/issues/142

We'll work on streamlining this!
