### ISSUE TITLE
Build from source on Pi: 502 Bad Gateway

### ISSUE THREAD

**Issue by ChristofferGreen** [gristlabs/grist-core#152]
Hi, I followed the documentation and did:

"yarn install

yarn run build:prod

yarn run install:python

yarn start"

doing "lynx localhost:8484" appears to  work. But I am having problems getting nginx to work with the following config (URL is the URL of the site, removed here for privacy reasons):

"
server {
  server_name URL;

  location / {
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;
    proxy_read_timeout      90;
    proxy_redirect          http://127.0.0.1:8484 URL;
  }
}
"

I get:

"
502 Bad Gateway
-------
nginx/1.14.2
"

Does anyone know what to do?

**Comment by paulfitz** [comment]
Not an nginx expert, so take this with a grain of salt. I'd have thought `proxy_pass` rather than `proxy_redirect`? https://github.com/gristlabs/grist-core/issues/142 has an example of an (eventually) working configuration. Might be worth setting `GRIST_HOST=0.0.0.0` just to be sure Grist will respond on any network interface.

**Comment by paulfitz** [comment]
Installation is a lot smoother these days, and there are arm64 docker images. Closing this, please reopen if there are still problems.
