### ISSUE TITLE
Unable to make API request from JavaScript fetch

### ISSUE THREAD

**Issue by dnsos** [gristlabs/grist-core#153]
## Problem
Hello, I am trying to fetch a document via the API as [outlined in the documentation](https://support.getgrist.com/api/#tag/docs/paths/~1docs~1{docId}/get). When I run my code in a local setup I get the following error in the browser console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://docs.getgrist.com/api/docs/<DOC_ID>. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 500.
```
## Steps to reproduce
1. Sign up for an account at https://www.getgrist.com/
2. Create a document and an API key
3. Serve the following `index.html` in your local setup (docId and API key omitted)

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
<script>
fetch(
    "https://docs.getgrist.com/api/docs/<YOUR-DOC-ID>",
    {
      headers: {
        Authorization: "Bearer <YOUR-API-KEY>",
      },
    }
  ).then((res) => {
    if (!res.ok) {
      throw new Error(`HTTP error! Status: ${ res.status }`);
    }
    return res.json();
  }).then((res) => console.log(res));
</script>
</body>
</html>
```

## Behaviour
The error message as shown above appears in the browser console.

## Expected behaviour
Receiving metadata about my requested doc. Using `curl` with the same doc and API key works just fine.

---

Perhaps I am missing something obvious. But the error message indicates that the `Access-Control-Allow-Origin` header is not present on the resource?

**Comment by paulfitz** [comment]
Hi @dnsos, thanks for the very clear description. Authentication by API key is currently limited to non-browser use, which is why we do not set `Access-Control-Allow-Origin`. An API key of this kind doesn't seem generally appropriate for web use, because the key would end up accessible to any viewer of the webpage, which is usually undesirable. No doubt there are exceptions where it would be ok, e.g. for sites that are only accessible by trusted users. Is that your case? We were planning to revisit this once we support API keys with more nuanced permissions.
If you're sure API keys embedded in the HTML source are fine for your use case, one option is to set up a little proxy to add the CORS header to responses. Examples:
* https://developers.cloudflare.com/workers/examples/cors-header-proxy
* https://github.com/Rob--W/cors-anywhere

I know having one more thing to wrangle is not an exciting option...
