### ISSUE TITLE
Embeddable form

### ISSUE THREAD

**Issue by anupamtandon** [gristlabs/grist-core#166]
Hello,
I am surprised that this data management tool does not have form system. Why is it ? 
It would be great if there was a form which could collect the data. 
Is it going to be implemented any time soon?

Thank you!!

**Comment by paulfitz** [comment]
Hi @anupamtandon. Forms are on our roadmap https://github.com/gristlabs/grist-core/issues/37. They haven't been a top priority since many users have had success using integrations - there's an example at https://support.getgrist.com/integrators/#example-storing-form-submissions

Native forms would make sense, I agree, and they are on our roadmap. In the meantime, recent improvements to granular access control are getting us closer to enabling spreadsheets for data collection without sign-ins, example: https://templates.getgrist.com/jd234iH1zDsL/Simple-Poll/p/1  Something better could be made by combining page [embedding](https://support.getgrist.com/embedding/) with a custom widget for a conventional form-like UI (someone would need to write this, but there are good open-source libraries for it).

**Comment by dumblob** [comment]
I agree with @paulfitz . OTOH if your needed something super simple and quick, http://demo.bpmn.io/form might be the way to go.

**Comment by anupamtandon** [comment]
So of us dont know programming or have very little technical aptitude. Hence any inbuilt native form would be so helpful. Any idea when is it going to be released?

**Comment by paulfitz** [comment]
The library behind that form demo looks neat @dumblob. @anupamtandon I'd be surprised if months go by without someone creating a custom widget to use that library or others like it to offer a form editor/viewer for Grist documents. Clean, fully integrated native forms are on our roadmap, but I can't guess at when they will happen - my apologies.

**Comment by fflorent** [comment]
I think this feature is now implemented. In case I am wrong, please tell me so I reopen the issue.
