### ISSUE TITLE
user.Name in self-hosted return empty

### ISSUE THREAD

**Issue by Vladimir-Va** [gristlabs/grist-core#182]
Hello.
In getgrist.com trigger formula user.Name return User Name value, but in docker self-hosted return empty value "". Wherein user.Email return User Email.

**Comment by georgegevoian** [comment]
Hi @Vladimir-Va. If you're using SAML for authentication, the user's name is derived from the given_name and surname attributes. Depending on your SAML provider, you may need to configure it to include this information in auth responses, so that the name is available in trigger formulas.

We do have a backlog item to improve this by using the name set on the Grist profile page in trigger formulas.

**Comment by Vladimir-Va** [comment]
Thank you @georgegevoian.
OMG again to dig into this terrible authentik.

**Comment by paulfitz** [comment]
`user.Name` is now more consistent, as of https://github.com/gristlabs/grist-core/commit/ce7eb05ed49430701f952831d9b578d97ad5fe94
