### ISSUE TITLE
Issue in updating the document via lan

### ISSUE THREAD

**Issue by opsbuddies** [gristlabs/grist-core#202]
Hello Team,

I have deployed the docker container on one machine and I am trying to access the application using private IP over port 8484(Via Lan). I am able to access the UI but as and when I try to update the document (from the remote system over LAN). I see this error 

Client error message =Unexpected quantifier.

**Comment by opsbuddies** [comment]
![Uploading 169202579...]

**Comment by opsbuddies** [comment]
![Uploading EB1D2135-0619-484A-AB9B-B5CD55F3E112.jpeg…]()

**Comment by opsbuddies** [comment]
![Uploading 38C4A44F-475D-48C8-990C-00AA8747B352.jpeg…]()

**Comment by opsbuddies** [comment]
![image](https://user-images.githubusercontent.com/104771163/169203677-41ca3a13-f0c5-4323-81eb-4d8bf64f3796.jpg)

**Comment by paulfitz** [comment]
Thanks for reporting this @opsbuddies. What browser is this with?

**Comment by opsbuddies** [comment]
@paulfitz Every browser I tried on remote computer, Just for reference - I tried Firefox and IE

**Comment by opsbuddies** [comment]
This is the error message in logs - Client error message =Unexpected quantifier.

I will share the detailed logs as well. But just to reinitiate my statement my docker container and application works good when using localhost:8484 This error only occurs when I try to access the UI from private IP on another system (Over LAN)

**Comment by opsbuddies** [comment]
![Upload-Error](https://user-images.githubusercontent.com/104771163/169445968-8b0505c9-e8da-4e77-8054-38e92d482025.jpeg)

**Comment by dsagal** [comment]
I did a little digging. It looks like you are using Firefox/68.0 (from a message in the screenshot), which is from 2019, and it indeed fails on parsing a regular expression, as Paul suspected. The regular expression comes from the `moment-guess` library, which uses "named capture groups". According to https://caniuse.com/mdn-javascript_builtins_regexp_named_capture_groups, those are supported on Firefox since version 78 (released June 2020), and not supported on IE at all.

Might you be able to update Firefox on the remote system from which you are trying to access Grist, and try again?

**Comment by opsbuddies** [comment]
@dsagal This helped, thank you so much we can close this issue.

Just a quick question will it support previous versions of mozilla/chrome? In further releases?

**Comment by paulfitz** [comment]
@opsbuddies I think we are unlikely to grow our support of older versions of browsers, since by their nature they matter to fewer and fewer people as time goes on. One option if you really need this would be to hire a developer to figure out the code changes needed for your situation.
