### ISSUE TITLE
Bug at import and strange behaviour

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#222]
Hi there,

I'm evaluating Grist, and I must say that I'm very impressed by the application: powerful, amazing UX and clean design.
I've made some tests all days, and I've encountered no bug until this one.

[This CSV file](https://github.com/gristlabs/grist-core/files/9171550/bentch.tableur.collaboratif.csv) is needed to reproduce the issue.

- first issue: when I import the file as "New Document" (so from home screen), only three of the six columns are imported (the first two and the last); note that when I import it as "New Table" (so from within a document page), I don't have this bug

- second, and strange issue: when I try to edit the new table after the bugged import and I try to add a column, I cannot edit this column settings at all, and strangely when I go to the code view, I see that the column as been added as a function and not as a property like the other columns (here, the new column is simply named `A`):

```python
import grist
from functions import *       # global uppercase functions
import datetime, math, re     # modules commonly needed in formulas


@grist.UserTable
class Bentch_tableur_collaboratif:
  fonctionnalite = grist.Text()
  priorite = grist.Numeric()

  def A(rec, table):
    return None
```

Hope that helps!

Congrats again for you work!

Yohan

**Comment by dsagal** [comment]
Hello Yohan! Thanks for the nice words about Grist! And thanks for reporting this.

The first issue, I believe, is real. In your document, the columns that were skipped are empty columns. I think Grist skips them intentionally, mainly to handle importing Excel files (where any sheet looks like it has lots of empty columns at the end). Since your columns have headers, though, I don't think Grist should skip importing them. We will look into it. Thanks for reporting!

The second issue is not a bug, just something a bit unusual. In Grist, completely empty columns are treated specially, in order to keep it easy to turn them into a data or formula column. Internally, they are represented as a formula column with an empty formula: that's what you are seeing in Code View. In the Creator panel, you'll see that the _type_ of the column is `Any`. You can change it to Numeric to have numeric formatting options, or Date, or anything else. You can also type in a number, date, or other text, and that will automatically turn it into a data column (no longer Empty) and set a matching type.

Hope this helps!

**Comment by yohanboniface** [comment]
Hi @dsagal and thanks for your answer :)

> I don't think Grist should skip importing them. We will look into it. Thanks for reporting!

Okay :)

> In Grist, completely empty columns are treated specially, in order to keep it easy to turn them into a data or formula column.

OK, thanks for clarification :) The weird thing is that the other day I was not able to change the column type by any way, and now I'm trying again and it's working perfectly! So let's for this time that the issue was me ;)

Thanks again for your answer :)

**Comment by LouisDelbosc** [comment]
Hello @dsagal and @yohanboniface,

We investigated and found where we skip the empty col during an import document.
Here a part of the flow:
- `oneStepImport` to import document page
- `_importFiles` and `_importFilesAsNewTable` with empty options and no transform rules
- `_transformAndFinishImport` but since we have no transform rule, we use `_makeDefaultTransformRule`

and here the default rule:
<img width="840" alt="Screenshot 2022-08-09 at 11 20 15" src="https://user-images.githubusercontent.com/11460746/183615240-ae9af229-7cf2-4cb2-85e8-324414f21ee4.png">
As you can see at L610, we skip the columns which are formula.

Here some logs:
![Screenshot 2022-08-09 at 11 18 06](https://user-images.githubusercontent.com/11460746/183615691-7c3e8c07-75ab-4cfb-86c0-2a3911f44599.png)

It's not very visible here but as @dsagal said empty columns are treated as formula (`isFormula: true`) and so are skipped.

If you want to change this behavior, you have yo change `_makeDefaultTransformRule`.

What behavior do you wish to have ? Or are you fine with the current one ?

**Comment by ronnix** [comment]
In addition to the previous comment, when the same CSV file is imported as a new table in an existing document, we don’t go through `oneStepImport` and in that case `_importFiles` is called with some transformRules, so the columns are not skipped.

**Comment by dsagal** [comment]
Thank you for digging into this. It's possible the line you identified (that skips empty columns) should just be removed. It makes the behavior of new-document and in-document imports consistent, and better (for a couple examples I checked). Let me check if there are some cases that it was intended to address.
