### ISSUE TITLE
How to get error detail of formula

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#231]
Hi,

Small edge case I guess: when I'm typing a formula but not all rows are in error, I haven't found a way to get the error detail.

Here is an example:

![Screenshot-20220729115053-1516x1738](https://user-images.githubusercontent.com/146023/181753095-827be2f1-146a-4bba-a890-794851bffda5.png)

(For the given formula, I now know that I just need to cast to `list` before trying to extend :) )

Thanks! :)

**Comment by paulfitz** [comment]
`Apply Formula to Data` is a very underdeveloped feature. It does need some attention by a designer. I think @dsagal has interest in a redesign, perhaps in coordination with some more thinking about the `Column Behavior` section (as opposed to a narrow series of bugfixes or polishing).

We're actually making a few changes related to formula editing right now. The changes are:

 * A new floating formula editor (https://github.com/gristlabs/grist-core/commit/da323fb741fdc171df394adb0bc6000083062995), currently you need a `GRIST_FORMULA_ASSISTANT=1` flag set to see it (flag will go away once feature is stable). Gives more space for editing, lets you move around the document while editing. I mention it because it involved some new work on previewing changes (though in the context of formula columns).

![Screenshot from 2023-07-10 06-57-14](https://github.com/gristlabs/grist-core/assets/118367/b5a648a1-2214-4223-a894-b0f37bd3935a)

 * An AI assistant for proposing formulas from natural text. Includes a mechanism for previewing the results of the formula. User's path to discovering/using the assistant is via instrumentation in the floating editor. Uses an OpenAI endpoint; have tried in past with various open source models and intend to support any of sufficient quality (haven't found any yet; there are one or two new ones I have my eye on).

Ideally, at a design level, we'd keep some coherence between how the user works with formulas and how changes are previewed. I know that's daunting for a narrow issue like "get error detail during transforms" and I wouldn't want the perfect to be enemy of the good. How big an annoyance is the issue @vviers ? If you and they have appetite for it, I'd suggest a fairly wide-ranging conversation with @anaisconce and @dsagal first, to get a sense of the big picture, then pick a pragmatic intermediate improvement that is pointed in a good direction. What do you think @anaisconce ?

**Comment by vviers** [comment]
> How big an annoyance is the issue @vviers ?

Not big at all once you've learned the workaround ! (Ctrl-Z, Create a new formula column, try and execute the transform formula in the new column, get error detail and do the formula tweaking there).

We can definitely wait for (and are interested in thinking about) a bigger formula editor revamp ! Maybe this discussion could be linked to https://github.com/gristlabs/grist-core/issues/266 ?

**Comment by vviers** [comment]
Thinking of closing this issue and making this part of a bigger "Re-design 'Apply formula'" 

FWIW, I almost never use "Apply formula" nowadays unless I am 100% sure of what I am doing, for data wrangling / cleaning I usually use the workflow I outlined above.
