### ISSUE TITLE
f-string support ?

### ISSUE THREAD

**Issue by yohanboniface** [gristlabs/grist-core#264]
Hi :)

Trying to use f-string in formula, I get this error:

![image](https://user-images.githubusercontent.com/146023/187882444-f7706200-02c5-499f-b693-c4891c7fccd9.png)

Absolutely not a high priority, but wondering if this is something that could work ?

![image](https://user-images.githubusercontent.com/146023/187882791-08226f9b-3d2e-4925-a6b7-1009fbc9f19f.png)

(I know I can use format :) )

By the way, the f-string may be too nerdy, so maybe it whould be better to have a `FORMAT(tx)` native method, that would internally do something like `txt.format(**rec)` ?

Yohan

**Comment by paulfitz** [comment]
The use of `$` in formulas is supported by a code translation step that doesn't know about f-strings: https://github.com/gristlabs/grist-core/blob/e95b2154051d5a8393bb005af49565d08117106a/sandbox/grist/codebuilder.py#L35-L40

A workaround would be to use the pure python syntax of `rec.A` and `rec.B` instead of `$A` and `$B`. @alexmojaki and @dsagal might know how practical it would be to support dollars in f-strings.

For adding a spreadsheet-style all-caps method, the best case is to find something familiar from other spreadsheets like Excel or Google Spreadsheets before considering inventing something new. Doing a quick search, I didn't see a good candidate, so inventing something like you propose is an option.

**Comment by alexmojaki** [comment]
The core problem is https://github.com/gristlabs/asttokens/issues/6

**Comment by dsagal** [comment]
This has been fixed since https://github.com/gristlabs/grist-core/commit/525613216c234bf70b4835a98b5741938715c6ca 🎉
