### ISSUE TITLE
public viewer needs to sign in?

### ISSUE THREAD

**Issue by j2l** [gristlabs/grist-core#31]
I'm trying public sharing.
On the docker version, the default user you@example.com is attributed to anonymous viewer. Since this user is the author, everyone has write access, can be fixed easily but unsecure by default :smile: 
On your hosted version, making it public for viewers:
![image](https://user-images.githubusercontent.com/65325/124149778-36d56580-da91-11eb-96a0-fdf668ef536a.png)

Then opening in another browser throws:

![image](https://user-images.githubusercontent.com/65325/124149868-48b70880-da91-11eb-8826-50f6de8af151.png)

well, if it's public ...

**Comment by dsagal** [comment]
In the hosted version, it must be that the public access setting didn't get saved. You need to click confirm when closing the sharing dialog for it to take effect -- could you check please?

**Comment by j2l** [comment]
Thanks @dsagal  It works now!
I'm pretty sure I did click confirm before testing, but since it works perfectly, I'm the one to blame :smile: 

For the docker version, how to get public access (no default you@example.com user)?
How to manage local users?

**Comment by paulfitz** [comment]
Hi @j2l, grist-core doesn't have a log-in system yet. It is in our roadmap to deal with this; our first priority was to make sure people could open and edit their own Grist documents locally, and our second priority is to make self-hosting easier. A good candidate for adding a log-in system yourself is https://github.com/vouch/vouch-proxy. We also have SAML support we could release, which would enable using a wide range of SSO providers - would that help? 

Once you've prepared a doc, it is possible to serve it to anonymous users by restarting with something like:
```
docker run -p 8484:8484 --env GRIST_DEFAULT_EMAIL=anon@getgrist.com -v $PWD/persist:/persist -it gristlabs/grist
```
But I doubt that's all you need, since you ask about managing users.

**Comment by j2l** [comment]
Thank you so much @paulfitz and the Grist team. You are very helpful, fast and willing to solve problems for the community, beyond your customers. I really appreciate this attitude. I really hope I will be able to support you financially very soon.

SAML support would be fantastic! 

My ultimate goal is to be able to have a backend with Grist and a PWA as frontend.
I tried multiple solutions so far and none is fully compatible with what I want (kind of todo list with group todos). It's for my brand new non profit organization in France to develop an open world and stories embedding real life challenges (realistis.com). It's not for an external client.
