### ISSUE TITLE
[Docs] POST new row creates multiple rows

### ISSUE THREAD

**Issue by j2l** [gristlabs/grist-core#32]
I'm sure I didn't fully get the doc at https://support.getgrist.com/api/#tag/Data-Tables
I'm working on your fantastic CRM tutorial with the API.
A POST at `http://0.0.0.0:8484/api/docs/hdNL4QimrQYxSeAmoFAaH7/tables/Contacts/data`  with BODY as {"name":"test"}
is successfully returning ... 4 rows:
[
    3,
    4,
    5,
    6
]
and therefore ...
![image](https://user-images.githubusercontent.com/65325/124297178-1540b080-db5b-11eb-97d1-574d7dd1f3cd.png)
:smile: 

AFAIU, I need to POST a single character, then record the response for the rowID, then PATCH this row?
There's some room for improvement :)

BTW, the response to the PATCH was `null` instead of the rowID.

**Comment by paulfitz** [comment]
POSTs are expecting per-column data, see the example payload on the far right here:
https://support.getgrist.com/api/#tag/Data-Tables/paths/~1docs~1{docId}~1tables~1{tableId}~1data/post
<img width="419" alt="Screen Shot 2021-07-02 at 12 36 11 PM" src="https://user-images.githubusercontent.com/118367/124304972-70aa7880-db32-11eb-80bb-51995e4061a0.png">
Likewise for patching.
You can omit the "id" column when posting, but not patching.

Thanks for the feedback. Users do find our API surprising, so I think we'll need to offer an alternative that is more in line with expectations. Internally, Grist is very column-oriented, which is why the API is as it is.

**Comment by j2l** [comment]
Ah, ok, it makes sense
Thank you again @paulfitz

**Comment by paulfitz** [comment]
There's a record-based API on the way now which should make working with Grist data via the API a bit more intuitive (see #75)
