### ISSUE TITLE
Error module @sqlite3-node

### ISSUE THREAD

**Issue by LouisDelbosc** [gristlabs/grist-core#395]
Hello,

I recently have the following issue. I suppose a new version of sqlite is breaking some dependencies. Do you know how to handle it ? Do you plan to upgrade your version ?

<img width="1038" alt="Screenshot 2023-01-06 at 13 36 41" src="https://user-images.githubusercontent.com/11460746/211013862-21102b1f-4e39-4f68-b930-06317401e228.png">

**Comment by paulfitz** [comment]
Hmm, it looks like the native part of the node-sqlite3 package didn't get compiled. Can you try removing `node_modules` and doing `yarn install` and `yarn run build:prod` again? If the problem recurs, you might be able to find an earlier error message saying what is going wrong with compiling node-sqlite3.

Separately, I have a personal fork with some upgrades, including pre-compiling binaries for many platforms. If there's a need I could look at landing this in @gristlabs/node-sqlite3 sooner rather than later.

**Comment by LouisDelbosc** [comment]
Thanks, it's working now
