### ISSUE TITLE
Bug on Card widget to display referenced row

### ISSUE THREAD

**Issue by LouisDelbosc** [gristlabs/grist-core#402]
As you can see in the following video, when no CMS is referenced, the bottom card is empty but as soon as we add a CMS, the bottom card stay as the last non-empty state.

In this example, the first row doesn't have any CMS but after updating the second row, we can see the bottom card showing an CMS.

https://user-images.githubusercontent.com/11460746/212965377-4e312350-2a21-4e6c-b345-1abfb5403341.mov

It's kind of an edge case, but the expected behavior should display a CMS when the row has a CMS and otherwise an empty row (in this particular case).

Do you agree ? Do you have a technical suggestion to tackle this issue ?

cc @vviers @yohanboniface @CamilleLegeron @paulfitz @dsagal

**Comment by yohanboniface** [comment]
Here is a small test case to reproduce the issue: https://nuage.yohanboniface.me/bug_empty_linked_card.grist

And a demo:
[Screencast from 2023-01-18 09-43-27.webm](https://user-images.githubusercontent.com/146023/213124536-2c9d696a-4bb3-4080-b176-29b6909c80de.webm)

**Comment by dsagal** [comment]
I can confirm the bug is easy to reproduce. This type of linking is called in code as "cursor linking". One observation is that when the Card widget is replaced by a Table (GridView) -- in which case cursor linking can still be used (but only to move a little triangle pointer in the linked GridView) -- there is no bug.

**Comment by LouisDelbosc** [comment]
@dsagal I think the behavior is actually the same (or not far): the widget show the data from the previous selected cell but does not select one for the actually selected cell.

I struggle quite a bit to fix this bug. I could see the data display is computed in here in `DisplayView` https://github.com/gristlabs/grist-core/blob/main/app/client/components/DetailView.js#L265 and I think it's compute here in `FieldBuilder` https://github.com/gristlabs/grist-core/blob/main/app/client/widgets/FieldBuilder.ts#L655 which build all cell.

However I first, I don't understand how the mapping between the table cursor and the display is done nor where it's done.
To be straightforward, I'm a bit lost and don't know where to look for. If you could help me it would be nice 😅

**Comment by dsagal** [comment]
Hi @LouisDelbosc ! I don't have an easy pointer, the reason for the bug isn't clear to me yet. But here are some points that may be useful.

For comparison with Table (GridView), here is the example with both a Card and a Table, linked the same way: https://public.getgrist.com/dcYeiCpkULXi/Bug-with-Empty-Linked-Card-GH-402. In the Card, a single record is shown but doesn't update. In the Table below, all records are shown but the "linked" one has a little black triangle in the row header. That triangle, I think, updates correctly. I.e. when you click on the third row (without an empty reference), the triangle disappears. But the cursor (the highlighted cell) does stay where it is in GridView too. The triangle behavior is what we want in DetailView, I think.

To understand the flow, here are some relevant bits of code:
- Cursor-linking starts from around here: https://github.com/gristlabs/grist-core/blob/f1a4404a60bc887152eda987a8a5607ca217b6b9/app/client/components/LinkingState.ts#L139. Clicking a different row in the source section gets the reference column value, and the `cursorPos` computed gets updated with the rowId from that reference.
- It _should_ then trigger an update in `BaseView.js` of `linkedRowId`, in https://github.com/gristlabs/grist-core/blob/f1a4404a60bc887152eda987a8a5607ca217b6b9/app/client/components/BaseView.js#L140, and it's used to update the cursor a few lines below.
- I am guesing the problem is that DetailView never uses `linkedRowId`. It seems to use cursor, but I think the Cursor class assumes that there is _always_ a cursor. That assumption comes from the idea that when navigating around a grid or deleting rows (or having rows deleted by another user), the cursor should never disappear entirely. Anyway, if there is a way to use `linkedRowId` instead, that might fix the problem.

**Comment by LouisDelbosc** [comment]
Hmm, it seems this bug is not quite easy haha.

When you select a cell in the `new row` (the last row) the cursor goes to the `new row` also. Could this be the default behavior when the link could not find the proper reference ?

**Comment by dsagal** [comment]
Yes, I think it should be. Ah, so maybe there is a simple fix! -- to change this line https://github.com/gristlabs/grist-core/blob/f1a4404a60bc887152eda987a8a5607ca217b6b9/app/client/components/BaseView.js#L144 to

```
  this.autoDispose(this.linkedRowId.subscribe(rowId => this.setCursorPos({rowId: rowId || 'new'})));
```

It is fairly specific to the cursor-linked setup, so hopefully doesn't affect other behavior. Having a test would be very helpful too, since clearly this situation isn't being captured by existing tests.

**Comment by LouisDelbosc** [comment]
> It is fairly specific to the cursor-linked setup, so hopefully doesn't affect other behavior. Having a test would be very helpful too, since clearly this situation isn't being captured by existing tests.

My manual tests seems to be working ! Thanks a lot @dsagal.
I will try to implement a specific test.

**Comment by LouisDelbosc** [comment]
Since the PR is merged, we can close this issue !
