### ISSUE TITLE
Exporting data when we are in "view as" mode not corresponding to user scenario

### ISSUE THREAD

**Issue by CamilleLegeron** [gristlabs/grist-core#432]
Hi,

If I have all rights on the documents, I am in "view as" mode of a user who sees only a part filtered of the data and I export data in CSV all data are exported. However the user, if he does this action, will only load the data he has access to. 

Maybe we could consider the ACL As User for this action. 
No urgency to it

**Comment by vviers** [comment]
Has there been a regression here ?

Here's what a user submitted :

<img width="1917" height="613" alt="Image" src="https://github.com/user-attachments/assets/1ac26b54-2a56-41c1-9f21-1741e0b6d26b" />

**Comment by dsagal** [comment]
Confirming that I can reproduce some situation of "View As" being incorrectly simulated for export. The one I reproduced involved columns that should've appeared as "CENSORED" but didn't. Several other situations (rules hiding columns or rows) worked correctly. Would it be possible to share the access rules for the table in question, to make sure we can reproduce this case as reported?

It may be a case that got missed when this was implemented in https://github.com/gristlabs/grist-core/commit/47e93eada3f548c3eb70d89e4f3903c26b7cc491.

**Comment by dsagal** [comment]
A fix is on the way! It turns out there was a bug where in some cases when using "View As", `user.Access` was that of the original user rather than the simulated one.

**Comment by maltevesper** [comment]
@dsagal Fix for the issue in the comment https://github.com/gristlabs/grist-core/issues/432#issuecomment-3270001225, or for the issue as a whole?

**Comment by dsagal** [comment]
This got fixed in September (since release v1.7.4). Closing, but reopen if you are seeing anything similar.

**Comment by dsagal** [comment]
> [@dsagal](https://github.com/dsagal) Fix for the issue in the comment [#432 (comment)](https://github.com/gristlabs/grist-core/issues/432#issuecomment-3270001225), or for the issue as a whole?

Fix for the issue as a whole. When using "View As", everything under the "View As" banner should respect the simulated user, including exports from the "..." menus. Above the banner -- in the "Share" menu -- it won't. Exports from the Share menu happen to respect the simulated user in the case of csv/tsv (because it's just a shortcut to export the currently-selected table), but export of the entire document to xlsx or download of a document is outside the scope of "View As" and reflects the actual user who is signed in. The position of the "View As" banner is intended to make it visually clear what's expected to be covered.
