### ISSUE TITLE
BUG? "Work on a copy" and "Document history" actions fail with self-signed certificates

### ISSUE THREAD

**Issue by Vinschni** [gristlabs/grist-core#464]
When using a self signed certificate "Work on a copy" fails with following error:
![Unbenannt](https://user-images.githubusercontent.com/340731/226175357-b405f6d0-2f89-47de-8ff6-dbcb3a675622.PNG)

**Comment by paulfitz** [comment]
Interesting scenario @Vinschni. This is one part of Grist making a request to itself, and being upset that it can't verify the server identity. I can't think of a way to get around this (apart from using e.g. a letsencrypt cert) without a code change. One option would be to add a flag that allows ignoring the problem (not great in general, but maybe ok in the kinds of situations where a self-signed cert is in use). Another would be to have Grist use a shortcut when in a single-server setup, since it can just talk to itself locally :-)

**Comment by Vinschni** [comment]
Understood.
Error occurs on using the document history, too
![error recover compare](https://user-images.githubusercontent.com/340731/226602242-3717a5d4-f38f-4471-90f7-8ce21f631042.PNG)

**Comment by paulfitz** [comment]
I came across this flag: https://nodejs.org/docs/latest-v14.x/api/cli.html#cli_node_tls_reject_unauthorized_value

Having read the documentation for it, and understanding the consequences, you could try setting:
```
NODE_TLS_REJECT_UNAUTHORIZED=0
```
In your Grist container's environment (e.g. as a `-e NODE_TLS_REJECT_UNAUTHORIZED=0` option to `docker`, or the equivalent for whatever tool you are using).

**Comment by Vinschni** [comment]
Thank you very much @paulfitz. It works as described.
I can report that both "Work on a copy" and "Document history" actions succeed as expected without error.

For anyone reading this, please be aware of the consequences of node.js is verifying that the SSL/TLS certificates have a proper and unbroken path up to a trusted "root" certificate.
