### ISSUE TITLE
Visually identify that a field is a drop-down list

### ISSUE THREAD

**Issue by CamilleLegeron** [gristlabs/grist-core#491]
Hi,
To help users to visually understand the structure of a Grist table it could be grate to add a small visual indication when the colmun is of type `choice list` or `choice`. May be with an a arrow down for `choice` type and a + for `choice list` type, like we use an = for formulas

 
![Peek 2023-04-13 17-31](https://user-images.githubusercontent.com/19594405/231811376-c8b225ea-a4b7-407e-a9e7-183a14922a89.gif)

**Comment by CamilleLegeron** [comment]
@anaisconce I think it's a question for you

**Comment by georgegevoian** [comment]
> @anaisconce I think it's a question for you

Hi @CamilleLegeron.

Anais is out of the office until April 24, but I think it's a good idea. Closely related to this is the lack of an icon for Reference List columns.

We do already have an icon we use for Choice and Choice List columns in the Column Type dropdown (see screenshot below). Perhaps we could use that one for Choice columns, and a variant of it for Choice List columns. One idea that would work for both Choice List and Reference List would be to take their existing icon and add a second checkmark/link, offsetting it slightly to the right so that it appears behind the first checkmark/link.

<img width="122" alt="Screen Shot 2023-04-13 at 11 47 07 PM" src="https://user-images.githubusercontent.com/85144792/231938199-a524db25-77a4-4700-9f44-f95734af5ab2.png">

**Comment by Vinschni** [comment]
Hi together, some thoughts from another perspective on that: In tables with many columns of low width this reduces space for content, increases visual clutter and is mainly helpful for users that are not familiar with the table they work with.
Did you think about indicating that in the column header instead of in every line?

**Comment by CamilleLegeron** [comment]
Hi @Vinschni and @georgegevoian, 

Thanks for your answers. It's true that it could take a lot of space, after thinking we might need it only on card view where there is much more space and there is only one instance at a time. For now a user need to click on the field to discover that there are choices. The first time they arrive in front of this view they do not understand, as they do not necessarily see other examples.

A chevron may be more understandable to the user, this is more common for this use. 
What do you think ?

**Comment by georgegevoian** [comment]
@CamilleLegeron what if the chevron was only shown in blank choice and choice list cells? I think that would address @Vinschni's concern.

**Comment by fflorent** [comment]
Hello there! I joined this week to the ANCT Données et Territoires, where also is @CamilleLegeron, to work on Grist :rocket:. Nice to meet you all! :wave: 

I intend to work on this enhancement

We suggest to place the chevron only when the field is displayed in the detail view. So the concerns raised about the lack of place would be taken into account (the table view would not be concerned by this enhancement).

This is how it is rendered as of my current progress:
[record4.webm](https://github.com/gristlabs/grist-core/assets/371705/85e20bd5-e42b-4ef3-b1d9-f94dfcb08748)

Unless you think it does not bother, I am attempting to also remove the chevron in the table view when the field is in edition mode.

**Comment by David-Fabijan** [comment]
What is the final state of this issue? I see there were commits to add this, but right now it seems that it's only in Form widgets that choices are obviously marked as such. The markings are not available in cards nor in tables (I agree that for tables it would mostly be taking up space, but it would also improve the experience of new users and be consistant with reference and attachment markings).
