### ISSUE TITLE
[Users Access] Grant the possibility for editors to manage users (add & delete users)

### ISSUE THREAD

**Issue by RaywanS** [gristlabs/grist-core#498]
Hi Grist team,

I'm Raywan, i'm a new member of the Beta.Gouv / ANCT team. Nice to meet you :-)

We are currently having more and more users on Grist, which is obviously a good thing.
But this creates an issue : teams are getting bigger and table owners wants to be autonomous on their users management (adding / removing them) are their teams are moving quickly.

For now, it's impossible for them to manage it as only administrators (basically, only the 8 members of our team) are able to do it.

Would it be possible to create an option to grant the possibility to a document owner to be able to manage users without becoming an admin?

Thanks,
Raywan

**Comment by dsagal** [comment]
Hello Raywan!

I'd like to clarify what you have in mind, please. Currently, any user who has OWNER role on a document or workspace is able to manage access to that document or workspace, but with some caveats:

1. Removing users is possible. If access is inherited from a parent (e.g. a document's users may be inherited from the workspace or the team site), the owner would need to remove this inheritance first, and could then re-add a subset of users manually. 

    To turn off inheritance, use the "Inherit Access" dropdown in the "Manage Users" dialog, and set it to `None`:

    <img width="322" alt="Screenshot 2023-04-20 at 4 03 51 PM" src="https://user-images.githubusercontent.com/1091143/233475691-fd9ad93b-1382-464f-9e2a-f3ca04ccd5ea.png">


2. Adding users is much more limited. An owner can always add users who are members of the Team Site. Those who have not yet been added to the Team Site are called "guests". By default, Grist allows 2 guests per document (which means that owners can add two such users to a doc) and 0 guests for workspaces.

To allow doc owners to add unlimited users, I see two approaches: either increase these guest limits (which may be possible without code changes for self-managed installs), or add a product feature that allows doc owners to add members to the Team Site.

Did I understand the need correctly?

**Comment by dsagal** [comment]
There is a somewhat related request here: https://github.com/gristlabs/grist-core/issues/375. It is about allowing user from a certain whitelisted domain to join a team site without an invitation. In that case it would also make sense for a doc owner to send an invitation to any user at such a domain, even if they are not yet a member.

**Comment by RaywanS** [comment]
Hey team,

Thank you for your quick answers!
Here are some precisions :

- It's definetly related to the #375 issue, yes.
- Our main issue is more about creating new access. A vast majority of our users do have the same email domain (anct.gouv.fr or nameofyourcounty.gouv.fr, for instance). Our main struggle here is that every time someone 

Just an example of the current situation : 

Michael is the owner of the ImportantProject1. 
He needs input of a lot of different people (let's say 30+) and it's getting bigger and bigger with time as those people change or new ones are added to the project.
Every time Michael needs to add users, he is contacting us by email.

What we would like to have is the possiblity to give Michael the right to give access to the document to new members of his team either :
-based on a whitelist domain (but he will still need to be able to manage the rights he is giving, as two people from the same domain won't necessary have the same rights on the documents).
- based on a "admin-like" feature, which is basically being able to do what we currently do as admins but only for his Team Site, without the rest of admins rules (like being able to change formulas for instance).

Is it clearer? Otherwise let me know! :)

Thanks,
Raywan

**Comment by vviers** [comment]
Somewhat related to this is the following issue that we have : we would like to have a subset of users that can manage users of a document but cannot modify it's structure (the `S` right in the ACL panel).

As of today, we cannot have both :  
- if a user is an `OWNER`, then we cannot remove the structure-edit `S` right from them
- if a user is an `EDITOR` without structure-edit, then they cannot manage users on the document

wdyt ? decoupling structure-editing from user management would make a lot of sense to us as many of our users need to control who can access their documents but would rather be reassured that they cannot "break" anything in the doc (e.g. formulas)

**Comment by vviers** [comment]
> To allow doc owners to add unlimited users, I see two approaches: either increase these guest limits (which may be possible without code changes for self-managed installs),

How would you increase guest limit on self-hosted ? Is there an env variable to do that ? (if not, I could do a PR to add one)

> or add a product feature that allows doc owners to add members to the Team Site.

Would this mean that all these new members of the team site would see (I'm assuming adding them as read-only at site level would be enough) all other documents that don't have inheritance turned off ?

**Comment by RaywanS** [comment]
Hi @Grist team, 

Any news for this one ? :-)

Thanks a lot!
Raywan for D&T team

**Comment by dsagal** [comment]
Hi! I think I can answer @vviers's questions from earlier, though I don't yet have a particular proposal for how best to address your requirements.

#### OWNERs and structure-edit permission.
 
> if a user is an OWNER, then we cannot remove the structure-edit S right from them

It is true that an OWNER can always change Access Rules, but the structure-edit (S) permission can in fact be removed from owners. You'd need to expand the special rule about structure editing in the UI, and set a different condition. For example, this prevents _anyone_ from editing the structure (the condition is simply `True`):

<img width="799" alt="Screenshot 2023-05-15 at 4 17 42 PM" src="https://github.com/gristlabs/grist-core/assets/1091143/0b0b3c41-70c2-42a5-8496-34e8a19b4044">

You can create conditions based on the user's email address, or based on [User Attributes](https://support.getgrist.com/access-rules/#user-attribute-tables) configured in the document.

This is not a security restriction because OWNERs can change rules to give themselves access, but it is a good way to prevent unintentional changes to structure. So it may or may not help you, depending on your requirements.

#### guest limit on self-hosted

> How would you increase guest limit on self-hosted ? Is there an env variable to do that ? (if not, I could do a PR to add one)

There is no env variable for this limit specifically, and actually I am a little unsure if what I'm saying is correct. The setting I have in mind is a limit called `maxSharesPerDoc`. It determines how many guests (users who aren't members of the org) a doc can be shared with. It is set in `app/gen-server/entity/Product.ts` for a number of plans, mostly for the purposes of our SaaS offerings, where it is set to 2. In the open-source version, I believe the default configuration sets `GRIST_DEFAULT_PRODUCT` to `Free`, which should associates team sites with a Product where this limit is unset. When unset, it should allow any number of guests. If you are seeing guests limited, it's possible that the default product was configured differently when you created your site, or that something doesn't work as intended.

#### what new members would see

> >  or add a product feature that allows doc owners to add members to the Team Site.

> Would this mean that all these new members of the team site would see (I'm assuming adding them as read-only at site level would be enough) all other documents that don't have inheritance turned off ?

If you add them with access level of "Viewer", then yes, your description is correct. They'll see all workspaces and documents that don't have inheritance turned off. At Team Site level, there is also an option to add members with access level of "Member" (shown in UI as "No default access"). Such users don't get any inherited access (so won't see anything by default), but may be added to any document individually, or to a workspace (and that access would be inherited by documents in that workspace).

**Comment by RaywanS** [comment]
Hi @dsagal ,

Thanks a lot for your answer. 

Quick update regarding the **OWNERs and structure-edit permission** : your workaround is working perfectly and we are now using it to deal with this kind of need. 

Thank you!
