### ISSUE TITLE
Strange filter behavior

### ISSUE THREAD

**Issue by wunter8** [gristlabs/grist-core#514]
I know when a sort is applied to a table, the rows update immediately when a value is changed. I expected the same thing to apply to filters. And it works with filters if the filtered column is changed in a different widget on the page UNTIL you change the filtered column in the filtered widget, then the row isn't hidden even if you change the value in a different widget. Reloading the page fixes the problem (until you change the filtered column in the filtered widget again).

Here is an example screen recording.

I want the table widget to only show tasks that are not done. The card widget is linked to the table widget.

If I toggle "Done" using the card widget, the row is correctly removed from/added to the table. 
If I toggle "Done" in the table, the row is NOT correctly removed from the table.

After toggling "Done" in the table for task 2, toggling "Done" using the card widget for task 1 still correctly removes task 1 from the table (so the issue appears to be based on specific rows, not the table as a whole).
BUT, after toggling "Done" in the table for task 2, toggling "Done" using the card widget for task 2 no longer has any effect.

If I switch to another page (or reload the same page), toggling "Done" using the card widget for task 2 works again, until I try toggling  "Done" in the table for task 2.

https://github.com/gristlabs/grist-core/assets/8421688/7c471a3a-d8bd-41e1-84e5-2fb960311102

This behavior seems inconsistent. I would expect any task marked as "Done" to disappear from the table, regardless of which widget made the change.

**Comment by dsagal** [comment]
This is actually intentional behavior, though should perhaps be adjusted or made optional. When you make a change to a cell that causes the edited row to be filtered out, that rows is explicitly exempted from the filtering, specifically to avoid it disappearing. In many cases, if an edit made a row disappear, that would be very confusing to the user. This is mainly useful for column types other than boolean (e.g. imagine filtering for prices >$1000, you type in "1", and the row disappears before you can even see what you typed).

Your case is a little different, since a filter on a boolean column essentially communicates the intent of "toggle whether or not this row appears". The current workaround is like you said -- reload the page, or switch to another page and back.

There are also cases with an opposite problem: in some cases, an edit may still cause a row to disappear causing bad confusion, e.g. if the page had other data linked to that row. (See https://community.getgrist.com/t/user-experience-issue-inconsistent-filtering-between-related-tables-causing-user-confusion/2307.)

Some options for possible improvements:
1. When there are such exempted rows, show a button to clear those exemptions (clearer and quicker than reloading the page)
2. Skip this behavior entirely for boolean columns.
3. Add an option to turn this behavior on or off.

**Comment by dsagal** [comment]
Thank you for the PR offer! It seems reasonable to me, but let's have @anaisconce weigh in before you start on a PR.

**Comment by anaisconce** [comment]
Of Dmitry's proposed solutions, I agree #2 seems like the surest bet. Thank you for the PR offer!
