### ISSUE TITLE
`GRIST_FORCE_LOGIN` breaks public access and iframe embedding

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#642]
Hey there 👋🏼 

The `GRIST_FORCE_LOGIN` env variable works wonders to disallow anonymous access to our grist instance. However, it has the side effect that documents that are `Public access` are no longer accessible by "anyone with the link", since even read-only users are redirected to the login page.

As a side effect, embedding a grist doc as an iframe also breaks when `GRIST_FORCE_LOGIN` is set.

Steps to reproduce : 
- spin up a Grist instance with `GRIST_FORCE_LOGIN=true`
- create a document, go to the sharing menu and turn `Public access` to `ON` and setup public access to read-only
- copy and paste the public link to a private browsing window, or try and embed it as an iframe

To me, this is unexpected behaviour as forcing users to log in to use Grist is conceptually different from sharing a read-only document online or embedding a doc via an iframe on another webpage.

**Comment by paulfitz** [comment]
There is a (somewhat) related issue that public sharing doesn't work with authentication wrappers implemented at the reverse proxy level https://github.com/gristlabs/grist-omnibus/issues/1

**Comment by fflorent** [comment]
It *seems* that removing this line *fixes* the issue: https://github.com/gristlabs/grist-core/blob/ee31764b839a2b05c8cbed27dda91ee1423d1e1c/app/server/lib/FlexServer.ts#L929

However, even if it seems like the [docHandler](https://github.com/gristlabs/grist-core/blob/ee31764b839a2b05c8cbed27dda91ee1423d1e1c/app/server/lib/AppEndpoint.ts#L218) check the access correctly, I am **really** unsure about the impacts of this removal.

@paulfitz What would be your thoughts about such a removal?

**Comment by paulfitz** [comment]
@fflorent that change would indeed make `GRIST_FORCE_LOGIN` ineffective on document URLs, which would match the expectations of @vviers. A user who is not logged in would not be forced to log in, and if public access to the doc has been granted, they would be given access to it - otherwise receive an error.

I think there would still be a mismatch of expectations for sharing at the workspace and site level. For example, a workspace publicly shared would still require a login.

I have some concern about changing the behavior of this flag, given its current documentation of `when set to 'true' disables anonymous access`. I could imagine users turning it on, and using "public" sharing to mean anyone who can log in to their SSO.

I wonder if a better solution would be to develop an alternative flag to control behavior on the default personal site. Forcing logins was a simple quick solution to avoid the excessively welcoming behavior we've added there to let people try the app out (focused on our SaaS), but maybe a flag that specifically changed that behavior on that one page would be better. Then access control on non-personal sites, workspaces, and docs can work as normal.

**Comment by fflorent** [comment]
Right, with your remark in mind, we may probably introduce another variable, like `GRIST_FORCE_LOGIN_EXCEPTIONS`, to let the admin choose what resources might bypass the GRIST_FORCE_LOGIN behavior.

So the admin may set `GRIST_FORCE_LOGIN_EXCEPTIONS="document,workspace,site"` or part of these values.

What do you think?

**Comment by paulfitz** [comment]
> So the admin may set GRIST_FORCE_LOGIN_EXCEPTIONS="document,workspace,site" or part of these values.
> Is that what you had in mind?

No, I was thinking more along the lines of `DO_ALL_THAT_WEIRD_FANCY_STUFF_TO_LET_ANON_USERS_TRY_OUT_GRIST=false` (haven't thought of a snappy name for it). So an anon user shows up on home page, Grist says hi, maybe gives a big signup/signon button, but not much else - no specially-added ability to import docs, no specially-added ability to create docs. Maybe `GRIST_ANON_PLAYGROUND=false` ?

The `GRIST_FORCE_LOGIN_EXCEPTIONS` approach sounds workable too. The "site" option would be a bit subtle, since you might want one setting for personal sites (especially anon's personal site, which is kind of a weird virtual thing) and another for regular named sites.
