### ISSUE TITLE
Starting Grist as a doc or home worker in Docker

### ISSUE THREAD

**Issue by fflorent** [gristlabs/grist-core#654]
I am working on attempting to see how to scale up Grist through Docker.

Going through the code, I identified a variable named `GRIST_SERVERS` which seems to tell what kind of server should be running.

In this script, this variable is taken into account: 
https://github.com/gristlabs/grist-core/blob/a18007ae7a3841275507add48e73a8e91a982fbd/app/server/mergedServerMain.ts#L158

However, the Dockerfile entrypoint is `sandbox/run.sh` which runs this file `stubs/app/server/server.ts` in which run mergedServerMain without taking into account this variable:
https://github.com/gristlabs/grist-core/blob/a18007ae7a3841275507add48e73a8e91a982fbd/stubs/app/server/server.ts#L109

If one wants to run a doc or home worker through Docker, what would be the right thing to do? Should the default entrypoint overridden to load config for gvisor and run directly `mergedServerMain`?

Thanks in advance :pray:

**Comment by paulfitz** [comment]
Looking at our own SaaS configuration, I see we call `mergedServerMain` directly. The `stubs/app/server/server.ts` was introduced when we open-sourced Grist as something with better defaults for typical use. There are default settings in `server.ts` that you'll want to keep (e.g. `GRIST_DEFAULT_PRODUCT` = `Free`). It might be worth your time making a few tweaks to `server.ts` so you can continue to use it but also specify the server type.

In general you are on the right path, a home server or doc worker is just a Grist instance with a subset of the possible endpoints. If you don't have a CDN for serving static assets, you can pair them with home, and have a pool of ["home", "static"] servers. That is the easy part, and can be stuck in front of a regular load balancer. You can separately have a pool of ["docs"] workers. Redis is essential for this, and some more careful routing, since individual doc workers need to be reachable for web socket connections.
