### ISSUE TITLE
Lost all tables after removing snapshot bucket

### ISSUE THREAD

**Issue by nsmathew** [gristlabs/grist-core#721]
A long story, please bear with me.

I have a self-hosted instance of grist as a container. I had setup document snapshots with a self-hosted minio container. It worked fine but I ran into issues once I added a region identifier(just a dummy name) in the minio console. This then prevented grist from starting as it was throwing a `S3Error: The authorization header is malformed; the region is wrong` exception. 

I then decided to remove the Minio instance to set it up from scratch and deleted the snapshots bucket as well. My assumption was I could start the snapshots in Grist afresh with the new Minio instance and a new access key. But after this action, grist did not show my  pages and tables, instead offered me a recovery option. Unfortunately, I did not this option and instead restarted my grist container. Now while the parent document exists, none of the pages and tables are shown. I just have 1 table with the default columns. I checked if disabling snapshots using the env variable would help, but no luck.

Any method of recovering my tables and data?

**Comment by dsagal** [comment]
Eek, sorry to hear this! Snapshots are more than for history -- when set up, the long-term storage you configure (like S3 or MinIO) becomes the authoritative repository of Grist documents, and the local disk of a server becomes the transient cache. Generally that's what you want, because you can stop and start a server (or even multiple), and all your documents are there because they come from the long-term storage.

That does mean it's important to have a backup of any important documents you have on a server before you start experimenting with snapshot configuration, because you are basically telling Grist that what's on the server is an unimportant temporary cache, while what's in S3 / MinIO is what matters.

(Don't punish yourself for not using the recovery option; I don't think it would've helped anyway if Grist didn't find your data. I think Grist is a bit too willing to start with an empty document when it can't find a document, instead of showing an error... This might be inherited from sqlite's behavior.)

I don't know the details of what happened in the scenario you describe. The typical server setup persists documents in `/tmp/grist`. Start by checking if there is anything there. Back up anything you find. Your data may still be there. You can check any `.grist` file using sqlite3 (e.g. `sqlite3 FILENAME.grist 'SELECT tableId FROM _grist_Tables'` will show all user tables in the document; if you only see `Table1`, then it's probably an empty one). If you find data you care about, you can upload any document like that to any running Grist installation via the browser, by importing from your Grist home page.

**Comment by nsmathew** [comment]
Thanks for the inputs. Lesson learned!!
There is no folder `grist` under `/tmp`. But I found `.grist` files which have the tables and data. I think I can salvage something from this. Is there any way to get hold of the formulas or the raw python code?

**Comment by dsagal** [comment]
The `.grist` files have everything, including formulas! It's the complete document. See this: https://support.getgrist.com/exports/#restoring-from-backup

**Comment by nsmathew** [comment]
Phew! The document was just a little older than the set of last major changes I made. I have gotten back 95% of my document. Thanks a lot for your help! I will close this issue.
