### ISSUE TITLE
How to calculate a fraction?

### ISSUE THREAD

**Issue by Jipok** [gristlabs/grist-core#747]
I want to store a fraction in a column. For example "1/32" "1/139". And then use this fraction through the formula. But I don't understand how. This seems like a simple task, but there is no eval or equivalent for an arithmetic expression. I understand that I can split the string into two parts and hardcode the calculation. But is there a nicer general solution?

```python
def eval_fraction(str):
    if '/' not in str:
        return float(str)
    numerator, denominator = str.split('/')
    return float(numerator) / float(denominator)
```

**Comment by fflorent** [comment]
Hi @Jipok 

`eval($fraction, {}, {})` should be a valid formula. But be sure that `$fraction` is a column of type `Text` (it can be set automatically to `Date` due to the presence of the slash).

![$fraction column set to type "Text"](https://github.com/gristlabs/grist-core/assets/371705/3038e054-63f5-41cb-bc3a-f642b2fba646)

However I find your solution valid, it makes sure the `$fraction` cell really contains a fraction or a float at the contrary of the call of the `eval()` function.

**Comment by Jipok** [comment]
Thanks for the quick response.

Can you tell me how to check that a cell is empty? Specifically, I have a column of links to another table and I highlight duplicates using the condition `len(Table2.lookupRecords(C=$C))>1`. However, empty cells are also highlighted (since there are several of them), which is very undesirable for me. I would like to highlight them in a different color. `ISBLANK` is not currently implemented.
![изображение](https://github.com/gristlabs/grist-core/assets/25588359/a382d5ec-aea1-47f1-8993-5bb9c63b0323)

**Comment by alexmojaki** [comment]
For detecting blank references I think `not $C` should work.

`eval` is very unsafe and should be avoided. Your `eval_fraction` looks good.

**Comment by Jipok** [comment]
> For detecting blank references I think not $C should work.

Works. Thx. It would be nice to see this in the documentation instead this:
![изображение](https://github.com/gristlabs/grist-core/assets/25588359/e4057cbb-3c30-42a8-960b-849124713fa2)
