### ISSUE TITLE
Allow webhooks to watch a single column for updates

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#763]
Following up on #762, it would be useful to be able to make webhooks trigger on updates for a specific column only

I don't think `ready column` does that — though it could maybe be made to do this using a (trigger?) formula ?

**Comment by alexmojaki** [comment]
+++++

You'd need to be able to watch for changes in several columns, not just one. But otherwise I agree with this, it would be generally useful and a good solution to #762. I think we could even consider a migration which configures existing webhooks to only watch the columns that exist in their table at the time, so that adding new columns won't trigger old webhooks.
