### ISSUE TITLE
Allow URLs with only a docID

### ISSUE THREAD

**Issue by vviers** [gristlabs/grist-core#768]
As a user, It would make sense to me that `https://mysite.grist.mydomain.com/o/docs/{docID}` would be enough for Grist to redirect me to the document (redirecting to the first page of the document sounds like a sensible default) instead of hitting me with a "Document not found" error. It would also make for smaller URLs which is always nice.

Why do we need to add the document title to the URL ? It it for security reasons ?

As always, happy to implement if we get your go-ahead :)

**Comment by paulfitz** [comment]
It is a good point. You can actually put anything as the document title, it doesn't have to be right, e.g. https://templates.getgrist.com/pwGTfus26ck8/whatever if that is any help. This is so that document titles can change without breaking URLs. There's also a /doc/ URL style like this: https://templates.getgrist.com/doc/pwGTfus26ck8

In all cases Grist redirects to the "canonical" URL with a title in it.

**Comment by vviers** [comment]
I agree that the discoverability of this option would be very low. My point with this issue is that most users _expect_ that `https://mysite.grist.mydomain.com/o/docs/{docID}` would work and not redirect them top an error page

I the need was only to be able to open a doc only knowing its docID, then I discovered that `https://mysite.grist.mydomain.com/o/docs/{docID}/anything` works :)
