### ISSUE TITLE
Conditional formatting

### ISSUE THREAD

**Issue by anaisconce** [gristlabs/grist-core#79]
Conditional formatting is useful for quickly conveying status information about certain rows or cells through color or other visual cues. Grist can do some of this (see https://community.getgrist.com/t/colour-code-table-cells/58) but systematic support for conditional formatting would be valuable.

**Comment by dumblob** [comment]
Instead of complicating the interface (non-tech-savvy people - i.e. vast majority - already gets overwhelmed by the [simple invoicing example](https://support.getgrist.com/examples/2020-08-invoices/ )).

Maybe it'd be enough if this was just an advanced widget served from your servers (as proposed in https://github.com/gristlabs/grist-core/issues/38#issuecomment-1046794975 )?

**Comment by anaisconce** [comment]
Conditional formatting is here! 🎉 Learn more in our help center: https://support.getgrist.com/conditional-formatting/
