### ISSUE TITLE
Feature request: Storing custom widget locally

### ISSUE THREAD

**Issue by springfielddatarecovery** [gristlabs/grist-core#803]
There may be a way to do this I am missing, but I think this falls under feature requests. If I understand correctly, a custom widget is the best way to accomplish solving the use case below. Right now, custom widgets require the widget to be hosted at a URL. It seems if custom widgets are just some text/html/python/whatever, they could be stored in the Grist database itself in a separate table, no need to rely on something else or arrange hosting for the widget.

Use case: I would like to make a custom widget which takes a field from a given card/entry, adds it to a url, and makes the URL clickable for the user (as a button or link). This would take them to our shipping label provider and pre-fill the customer's name. I would gladly have this url/button show in an existing widget like the card view, but my understanding is that those can't be modified in that way.

Also, is there some way to donate to development? OpenCollective, etc? This tool is AMAZING and I would like to contribute to development on an ongoing basis.

**Comment by alexmojaki** [comment]
> There may be a way to do this I am missing, but I think this falls under feature requests. If I understand correctly, a custom widget is the best way to accomplish solving the use case below. Right now, custom widgets require the widget to be hosted at a URL. It seems if custom widgets are just some text/html/python/whatever, they could be stored in the Grist database itself in a separate table, no need to rely on something else or arrange hosting for the widget.

It's definitely possible to construct a widget that depends on the hosting server doing some custom backend logic, in which case storing HTML in the Grist document wouldn't work. But you're right that in practice, a lot of widgets are (or could be, with a little effort) a single HTML file.

There are custom widgets that essentially do what you're saying though. The official [HTML Viewer](https://support.getgrist.com/widget-custom/#html-viewer) widget renders the HTML in the selected cell of a regular table. And @berhalak's [fiddle](https://berhalak.github.io/my-widgets/fiddle/index.html) ([source](https://github.com/berhalak/my-widgets/tree/main/fiddle)) stores HTML and JS in the widget's configuration which is in a hidden database table.

> Use case: I would like to make a custom widget which takes a field from a given card/entry, adds it to a url, and makes the URL clickable for the user (as a button or link). This would take them to our shipping label provider and pre-fill the customer's name. I would gladly have this url/button show in an existing widget like the card view, but my understanding is that those can't be modified in that way.

You *could* use the HTML viewer for this, e.g. if you wanted the button to look fancy. But you can also just have a formula which returns the URL and that will be a clickable link. If you want to display custom text instead of a messy URL, just [format a text column as a hyperlink](https://support.getgrist.com/col-types/#hyperlinks).

> Also, is there some way to donate to development? OpenCollective, etc? This tool is AMAZING and I would like to contribute to development on an ongoing basis.

Thank you! I see you're sponsoring on GitHub, did you find that after asking, or are you saying you'd prefer a different donation platform?

**Comment by springfielddatarecovery** [comment]
I found the sponsor option after I made my issue :). Thank you for the tips and advice, I'll try some of these methods it seems a custom widget may be a bit overkill for this use case.
