### ISSUE TITLE
GRIST_LIST_PUBLIC_SITES and GRIST_TELEMETRY_LEVEL environment variables type error

### ISSUE THREAD

**Issue by hatalmasalma** [gristlabs/grist-core#876]
Version: grist:latest and grist_ee from docker hub

### 1.Error
The documentation states:
GRIST_LIST_PUBLIC_SITES:
"if set to true, sites shared with the public will be listed for anonymous users. Defaults to false."

```
root@user:/home/user# docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.baserow.environment.GRIST_LIST_PUBLIC_SITES contains true, which is an invalid type, it should be a string, number, or a null
```

### 2.Error
The documentation states:
GRIST_TELEMETRY_LEVEL:
"the telemetry level. Can be set to: off (default), limited, or full."
```
root@user:/home/user# docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.baserow.environment.GRIST_TELEMETRY_LEVEL contains false, which is an invalid type, it should be a string, number, or a null
```

### File contents:
<details>
<summary>docker-compose.yml (nothing special I think)</summary>

```
services:
  baserow:
    container_name: grist
    image: gristlabs/grist:latest
    environment:
        APP_HOME_URL: 'http://localhost'
        GRIST_DEFAULT_EMAIL: asd@example.com
        GRIST_SESSION_SECRET: secret
        GRIST_LIST_PUBLIC_SITES: true
        GRIST_MAX_UPLOAD_ATTACHMENT_MB: 20480
        GRIST_PAGE_TITLE_SUFFIX: _blank
        GRIST_SERVERS: home,docs,static,app
        GRIST_TELEMETRY_LEVEL: off
        GRIST_SUPPORT_EMAIL: dsa@example.com
        GRIST_SNAPSHOT_KEEP: 1
    ports:
      - "8484:8484"
    volumes:
      - grist-persist:/persist
volumes:
  grist-persist:
```

</details>

**Comment by fflorent** [comment]
I think it's not a problem in the documentation, but rather a limitation of the `docker-compose.yml` format:
https://devops.stackexchange.com/a/542

(TL;DR: both `true` and `off` are converted to booleans by the Yaml parser, which has led the docker-compose project to forbid them for environment variables due to confusions)

You may surround the values with double quotes, which may fix you problem according to [this answer](https://devops.stackexchange.com/a/15780). Or you can put the env variable to a dedicated file and reference this file in an env_file as suggested in [this answer](https://devops.stackexchange.com/a/542).

**Comment by hatalmasalma** [comment]
Wow, thank you very much for the fast and detailed answer! <3
It solved the errors, so I'm closing the issue.

**Comment by fflorent** [comment]
Glad it worked. You're welcome! :)
