### ISSUE TITLE
Summary table from a reference column

### ISSUE THREAD

**Issue by paparapapapapa** [gristlabs/grist-core#983]
Hi, my spreadsheets is composed of three pages:
1. Assets specifications
2. Operations
3. Statistics

The first column of _Operations_ is a reference column to the first column of _Assets specification_, which is _Asset name_.

When, in _Statistics_, I try to summarise all _Operations_ by _Asset name_ using a table widget, the _Asset_ column is populated automatically like this (i.e. no asset names but a reference to a list):

<img width="336" alt="Screenshot 2024-05-14 alle 18 07 15" src="https://github.com/gristlabs/grist-core/assets/56885560/4e0fa07c-f168-4f37-b74f-750c5e24f53b">

Is this a bug or am I missing something?

Thank you.

**Comment by dsagal** [comment]
For any reference column (in particular, the `Asset` column in _Operations_, or the `Asset` column of the summary table),  you can set the `SHOW COLUMN` value to _Asset name_, so that the reference values show the asset name. This is shown, for example, in the screenshot in documentation here: https://support.getgrist.com/col-refs/#understanding-reference-columns.

Does that solve your issue?

**Comment by paparapapapapa** [comment]
Oh yes it does, I totally overlooked that. Thank you very much.
